import type { ChangeEvent, FormEvent, ReactElement } from 'react';
import { useEffect, useState } from 'react';
import { Card } from '@starter/ui';
import { adminApi, type RetailerDto } from '../admin-api';

const emptyForm = { name: '', slug: '', description: '', logoUrl: '', websiteUrl: '', active: true };

export const RetailersAdminSection = ({ accessToken }: { accessToken: string }): ReactElement => {
  const [items, setItems] = useState<RetailerDto[]>([]); const [page, setPage] = useState(1); const [total, setTotal] = useState(0); const [search, setSearch] = useState(''); const [active, setActive] = useState(''); const [editing, setEditing] = useState<RetailerDto | null>(null); const [form, setForm] = useState(emptyForm); const [loading, setLoading] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const load = async () => { setLoading(true); setError(null); try { const q = new URLSearchParams({ page: String(page), limit: '10' }); if (search) q.set('search', search); if (active) q.set('active', active); const data = await adminApi.listRetailers(accessToken, q); setItems(data.items); setTotal(data.total); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudieron cargar mayoristas'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [accessToken, page, active]);
  const update = (field: keyof typeof emptyForm) => (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setForm((current) => ({ ...current, [field]: field === 'active' ? event.target.value === 'true' : event.target.value }));
  const edit = (item: RetailerDto) => { setEditing(item); setForm({ name: item.name, slug: item.slug, description: item.description ?? '', logoUrl: item.logoUrl ?? '', websiteUrl: item.websiteUrl ?? '', active: item.active }); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(null); setMessage(null); try { const payload: { name: string; active: boolean; slug?: string; description?: string; logoUrl?: string; websiteUrl?: string } = { name: form.name, active: form.active }; if (form.slug) payload.slug = form.slug; if (form.description) payload.description = form.description; if (form.logoUrl) payload.logoUrl = form.logoUrl; if (form.websiteUrl) payload.websiteUrl = form.websiteUrl; if (editing) await adminApi.updateRetailer(accessToken, editing.id, payload); else await adminApi.createRetailer(accessToken, payload); setMessage('Mayorista guardado correctamente'); setEditing(null); setForm(emptyForm); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar'); } finally { setLoading(false); } };
  return <div style={{ display: 'grid', gap: '1rem' }}><h2>Mayoristas</h2>{message ? <p style={{ color: 'green' }}>{message}</p> : null}{error ? <p style={{ color: 'crimson' }}>{error}</p> : null}<form onSubmit={submit} style={{ display: 'grid', gap: '.5rem' }}><label>Nombre<input required minLength={2} maxLength={120} value={form.name} onChange={update('name')} /></label><label>Slug<input value={form.slug} onChange={update('slug')} placeholder="se genera automáticamente" /></label><label>Descripción<textarea maxLength={500} value={form.description} onChange={update('description')} /></label><label>Logo URL<input type="url" value={form.logoUrl} onChange={update('logoUrl')} /></label><label>Sitio web<input type="url" value={form.websiteUrl} onChange={update('websiteUrl')} /></label><label>Estado<select value={String(form.active)} onChange={update('active')}><option value="true">Activo</option><option value="false">Inactivo</option></select></label><button disabled={loading} type="submit">{editing ? 'Actualizar' : 'Crear'} mayorista</button>{editing ? <button type="button" onClick={() => { setEditing(null); setForm(emptyForm); }}>Cancelar</button> : null}</form><Card title="Listado"><div style={{ display: 'flex', gap: '.5rem', flexWrap: 'wrap' }}><input placeholder="Buscar" value={search} onChange={(e) => setSearch(e.target.value)} /><select value={active} onChange={(e) => setActive(e.target.value)}><option value="">Todos</option><option value="true">Activos</option><option value="false">Inactivos</option></select><button disabled={loading} type="button" onClick={() => { setPage(1); void load(); }}>Buscar</button></div>{loading ? <p>Cargando...</p> : null}{items.length === 0 ? <p>No hay mayoristas.</p> : <div style={{ overflowX: 'auto' }}><table style={{ width: '100%', minWidth: 640 }}><thead><tr><th>Nombre</th><th>Slug</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.slug}</td><td>{item.active ? 'Activo' : 'Inactivo'}</td><td><button type="button" onClick={() => edit(item)}>Editar</button></td></tr>)}</tbody></table></div>}<button disabled={page <= 1 || loading} onClick={() => setPage((p) => p - 1)}>Anterior</button><span> Página {page} / {Math.max(1, Math.ceil(total / 10))} </span><button disabled={page >= Math.ceil(total / 10) || loading} onClick={() => setPage((p) => p + 1)}>Siguiente</button></Card></div>;
};
